version: '3'
services:
  blog-node:
    build: .
    volumes: 
    - .:/usr/src/app
    ports:
    - "8082:3000"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    restart: always